#!/usr/bin/env python3
"""Assemble the single-file Crossings tool: inject data + world map into _template.html.
Edit _template.html, never index.html. Run: python3 build.py
Inputs live one dir up in /tmp/bf-build/ (the data pipeline output)."""
import json, re, os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = HERE  # flat dir: data sits alongside build.py

def load(name): return json.load(open(os.path.join(DATA, name)))

C   = load('countries.json')
P   = load('pairs.json')
G   = load('global.json')
V   = load('verdict.json')
TD  = load('today.json')
MAP = {k: v for k, v in load('mapid_to_iso3.json').items() if v}

# ---- prepare the world SVG ----
svg = open(os.path.join(DATA, 'world.svg')).read()
svg = svg[svg.index('<svg'):svg.rindex('</svg>') + 6]          # strip xml/comment preamble
# root <svg ...> tag: give it our id, make it responsive, drop fixed px size
m = re.match(r'<svg\b[^>]*>', svg, re.S)
head = m.group(0)
head2 = re.sub(r'\s(width|height)="[^"]*"', '', head)
if 'id=' not in head2:
    head2 = head2[:4] + ' id="mapsvg" preserveAspectRatio="xMidYMid meet"' + head2[4:]
else:
    head2 = re.sub(r'id="[^"]*"', 'id="mapsvg"', head2, count=1)
svg = head2 + svg[m.end():]
# neutralize the baked-in light fill so CSS/JS own the color
svg = svg.replace('fill:#f2f2f2;', '').replace('fill:#f2f2f2', '')
# inject the no-data hatch pattern right after the opening tag
defs = ('<defs><pattern id="nodata" width="5" height="5" patternUnits="userSpaceOnUse" '
        'patternTransform="rotate(45)"><rect width="5" height="5" fill="#20283a"/>'
        '<line x1="0" y1="0" x2="0" y2="5" stroke="rgba(233,240,253,.42)" stroke-width="1.2"/></pattern>'
        '<pattern id="gaphatch" width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">'
        '<rect width="5" height="5" fill="#0e2349"/>'
        '<line x1="0" y1="0" x2="0" y2="5" stroke="rgba(232,161,58,.5)" stroke-width="1.2"/></pattern></defs>')
svg = re.sub(r'(<svg\b[^>]*>)', r'\1' + defs, svg, count=1)

# ---- data block ----
def j(o): return json.dumps(o, separators=(',', ':'))
data_js = (f"const C={j(C)};\nconst P={j(P)};\nconst G={j(G)};\n"
           f"const V={j(V)};\nconst TD={j(TD)};\nconst MAP={j(MAP)};")

HEADER = ("<!--\n  Crossings - generated by build.py from _template.html. Edit the template, then: python3 build.py\n"
          "  Data: DEMIG VISA v1.4 (Oxford International Migration Institute, 2015); Passport Index dataset (ilyankou, MIT).\n"
          "  Map outlines: world-map-country-shapes by Luca Lischetti (sirLisko), MIT, based on simplemaps.com:\n"
          "  Copyright (c) 2015 Pareto Software, LLC DBA Simplemaps.com - MIT License.\n-->\n")
tpl = open(os.path.join(HERE, '_template.html')).read()
out = HEADER + tpl.replace('<!--WORLD_SVG-->', svg).replace('/*DATA_BLOCK*/', data_js)

dest = os.path.join(HERE, 'index.html')
open(dest, 'w').write(out)
kb = os.path.getsize(dest) // 1024
print(f"built index.html  {kb} KB  ({len(C)} countries, {len(P)} passport rows, {len(MAP)} map joins)")
