# Site settings
title: Hi! I'm Ajin
email: contact@ajin.im
url: https://www.ajin.im
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "<b>Transcreator - Copywriter - Localization Manager<br />
From 민망한 콩글리쉬 To 한류 Superstar <br />Go Global with Ajin Im</b>"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ajin Im
  location: Location
  social: Around the Web
  credits:
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/propagandaformyself
#- title: blog url: https://propagandaformyself.com
  - title: reddit
    url: https://reddit.com/u/propagandaformyself
  - title: github
    url: http://github.com/mobetter20

# Postal address (add as many lines as necessary)
address:
  - line: based in Seoul, South Korea
  - line: but matered the art of remote communication

# Credits content
credits: I'll like to thank the housemate whom I'm engaged to for this website and my <a href="https://blackballoons.github.io/">blog</a>

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
#for plugin:
