#!/usr/bin/env python3
"""Build the single-file Joseon Review app.

Reads _template.html and inlines the raw contents of data.json and
lookups.json into the two `<script type="application/json">` placeholders,
then writes index.html. The data is parsed once on load in the browser, so
the artifact is a single self-contained file.

Do NOT edit index.html by hand: it is generated from _template.html. Edit the
template (markup + CSS + JS) and re-run `python3 build.py`.
"""

import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
TEMPLATE = HERE / "_template.html"
DATA = HERE / "data.json"
LOOKUPS = HERE / "lookups.json"
OUT = HERE / "index.html"

BANNER = (
    "<!-- GENERATED by build.py from _template.html + data.json + lookups.json"
    " — DO NOT EDIT this file directly. -->"
)

DATA_MARK = "<!--DATA-->"
LOOKUPS_MARK = "<!--LOOKUPS-->"


def main() -> int:
    template = TEMPLATE.read_text(encoding="utf-8")
    data = DATA.read_text(encoding="utf-8")
    lookups = LOOKUPS.read_text(encoding="utf-8")

    for mark in (DATA_MARK, LOOKUPS_MARK):
        if mark not in template:
            print(f"ERROR: marker {mark} not found in {TEMPLATE.name}", file=sys.stderr)
            return 1

    # Replace placeholders with the raw JSON file contents. The JSON sits
    # inside <script type="application/json"> tags, so it is inert text to the
    # HTML parser; no escaping is needed beyond not containing the literal
    # substring "</script>" (JSON data does not).
    html = template.replace(DATA_MARK, data.strip())
    html = html.replace(LOOKUPS_MARK, lookups.strip())

    # Insert the DO-NOT-EDIT banner immediately after the doctype line.
    lines = html.split("\n", 1)
    if not lines[0].lower().startswith("<!doctype"):
        print("ERROR: template must begin with <!doctype html>", file=sys.stderr)
        return 1
    rest = lines[1] if len(lines) > 1 else ""
    html = lines[0] + "\n" + BANNER + "\n" + rest

    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUT.name}  ({OUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
