export const words={
 insert:{jp:'お金を入れてください',reading:'おかねを いれてください',roman:'okane o irete kudasai',meaning:'Please insert money.',detail:'お金 is money. 入れて is “put in”; ください makes it a request. The machine expects money before a menu selection.',extra:'You will also see 投入 (とうにゅう), “insertion.” 投入金額 is the amount inserted. Korean 투입 uses the same characters, 投入.'},
 credit:{jp:'投入金額',reading:'とうにゅうきんがく',roman:'tōnyū kingaku',meaning:'Amount inserted / available credit.',detail:'Here the display shows the money still available to spend. After a purchase, it goes down.',extra:'投入 = putting in; 金額 = an amount of money. Korean 투입 / 금액 share these character compounds.'},
 ticket:{jp:'食券',reading:'しょっけん',roman:'shokken',meaning:'Meal ticket.',detail:'食 means food or eating; 券 means a ticket. You buy the ticket here and give it to the staff.',extra:'Korean 식권 is the same word written 食券. The small っ in しょっけん gives the doubled “k” in shokken.'},
 notice:{jp:'食券は店員にお渡しください',reading:'しょっけんは てんいんに おわたしください',roman:'shokken wa ten’in ni owatashi kudasai',meaning:'Please hand your meal ticket to a staff member.',detail:'店員 is a shop staff member. This shop asks you to hand over tickets before taking a seat.',extra:'This is the rule of this fictional shop. Other restaurants may collect tickets in the queue or use electronic orders. Read the posted instructions.'},
 coin:{jp:'硬貨',reading:'こうか',roman:'kōka',meaning:'Coins.',detail:'This machine accepts ¥10, ¥50, ¥100 and ¥500 coins. The narrow vertical slot is for coins, not banknotes.',extra:'硬 means hard; 貨 means currency or goods. 紙幣, banknotes, goes into the wider horizontal slot.'},
 bill:{jp:'紙幣',reading:'しへい',roman:'shihei',meaning:'Banknotes.',detail:'This machine accepts ¥1,000 and ¥2,000 notes. A ¥5,000 or ¥10,000 note will not work here.',extra:'紙 is paper. 千円札 (せんえんさつ, sen’en-satsu) is a ¥1,000 note. Some other machines accept larger notes; check the denominations printed by the slot.'},
 cash:{jp:'現金のみ',reading:'げんきん のみ',roman:'genkin nomi',meaning:'Cash only.',detail:'のみ means “only.” There is no card reader on this machine.',extra:'現金 is cash; Korean 현금 uses the same characters. Do not assume that every physical-button machine is cash-only: some have added payment readers.'},
 selling:{jp:'発売中',reading:'はつばいちゅう',roman:'hatsubaichū',meaning:'On sale / selling now.',detail:'The machine is operating. This is different from an individual menu item being sold out.',extra:'The adjacent つり銭切れ indicator means “out of change.” It is not lit in this practice machine.'},
 sold:{jp:'売切',reading:'うりきれ',roman:'urikire',meaning:'Sold out.',detail:'This item is unavailable, however much money you insert. Choose another button.',extra:'Often also written 売り切れ. 売 is sell; 切れ conveys running out. A red 売切 lamp is different from an unlit affordable-selection lamp.'},
 change:{jp:'おつり・返却',reading:'おつり・へんきゃく',roman:'otsuri / henkyaku',meaning:'Change / return.',detail:'Press this to return the money you have not spent. It does not cancel tickets you already bought.',extra:'おつり is change from a payment. 返却 is returning something. On this machine you must ask for change; some machines return it automatically.'},
 outlet:{jp:'取出口',reading:'とりだしぐち',roman:'toridashiguchi',meaning:'Collection slot / outlet.',detail:'Take out what the machine has dispensed. Tickets and change have separate collection points here.',extra:'取出し is taking something out; 口 is an opening. You may also see 取出口 written 取り出し口.'},
 printing:{jp:'発券中',reading:'はっけんちゅう',roman:'hakkenchū',meaning:'Printing a ticket.',detail:'Your purchase has already been made. Wait briefly for the paper ticket to reach the outlet.',extra:'発券 means issuing a ticket; 中 means “in progress.” It also appears in 処理中 (processing).'},
 shoyu:{jp:'醤油らーめん',reading:'しょうゆ らーめん',roman:'shōyu rāmen',meaning:'Shoyu ramen: soy-sauce-seasoned broth.',detail:'Here, clear chicken broth seasoned with soy sauce, with pork, bamboo shoots, nori and spring onion. No egg unless you add one.',extra:'Shoyu names the seasoning, not the entire stock. A shoyu ramen may use chicken, pork, seafood or a mixture. 醤油 is also the soy sauce you see on a supermarket bottle.',photo:true},
 shio:{jp:'塩らーめん',reading:'しお らーめん',roman:'shio rāmen',meaning:'Shio ramen: salt-seasoned broth.',detail:'This shop’s other basic bowl uses salt seasoning with its chicken broth. It is not simply noodles in salted water.',extra:'Shio describes the seasoning style. It does not tell you all the ingredients, nor does it guarantee a lower sodium content.'},
 egg:{jp:'味玉',reading:'あじたま',roman:'ajitama',meaning:'Seasoned egg.',detail:'A separate topping ticket for one marinated egg. Give it to the staff along with your ramen ticket.',extra:'A shortened form of 味付け玉子 (あじつけたまご), “seasoned egg.” 味玉入り on a ramen button means the egg is already included.'},
 nori:{jp:'のり',reading:'のり',roman:'nori',meaning:'Dried seaweed.',detail:'An extra serving of the dried seaweed sheets used as a topping. This is an add-on, not a bowl of ramen.',extra:'Also written 海苔. It is the same nori used around many onigiri rice balls.'},
 menma:{jp:'メンマ',reading:'メンマ',roman:'menma',meaning:'Seasoned bamboo shoots.',detail:'A ramen topping. The extra portion is sold out in this practice shop.',extra:'The red 売切 lamp tells you availability. In this simulation, the base bowls still contain their usual garnish; only the extra portion is unavailable.'},
 large:{jp:'大盛',reading:'おおもり',roman:'ōmori',meaning:'A larger serving.',detail:'Here, a separate ticket to increase the noodles in your bowl. Give both tickets to the staff.',extra:'大盛 is not 替玉 (かえだま). 大盛 makes the initial serving bigger; 替玉 is another serving of noodles, usually added to broth you kept.'},
 rice:{jp:'ライス',reading:'ライス',roman:'raisu',meaning:'Rice.',detail:'A separate bowl of plain rice to eat with your ramen.',extra:'The smaller portion is 小ライス (しょうライス). The 小 on the button means small.'},
 'small-rice':{jp:'小ライス',reading:'しょうライス',roman:'shō raisu',meaning:'Small rice.',detail:'A small bowl of plain rice. It is a side, not a smaller ramen.',extra:'小 means small. Portion words can be written as 大 / 中 / 小, or 並 / 大盛, depending on the shop.'},
 special:{jp:'特製',reading:'とくせい',roman:'tokusei',meaning:'The shop’s special version.',detail:'In this fictional shop, the special bowl includes an egg, extra pork and extra nori.',extra:'特製 is not a universal recipe. Check the shop’s description. Korean 특제 is the same character compound.'},
 please:{jp:'お願いします',reading:'おねがいします',roman:'onegai shimasu',meaning:'Please / I’d like this, please.',detail:'A natural thing to say as you hand over your tickets. You can simply hand them over, too.',extra:'You have already paid. The paper tickets tell the staff what you ordered. Keep your change and wait for the staff’s seating guidance.'}
};
for(const base of ['shoyu','shio']){
 words[`egg-${base}`]={...words.egg,jp:`味玉${base==='shoyu'?'醤油':'塩'}`,reading:`あじたま${base==='shoyu'?'しょうゆ':'しお'}`,roman:`ajitama ${base==='shoyu'?'shōyu':'shio'}`,meaning:`${base==='shoyu'?'Shoyu':'Shio'} ramen with a seasoned egg.`,detail:'This is a complete bowl with an egg included. A separate 味玉 ticket would buy another egg.'};
 words[`special-${base}`]={...words.special,jp:`特製${base==='shoyu'?'醤油':'塩'}`,reading:`とくせい${base==='shoyu'?'しょうゆ':'しお'}`,roman:`tokusei ${base==='shoyu'?'shōyu':'shio'}`};
}
const add=(id,jp,reading,roman,meaning,detail,extra='')=>words[id]={jp,reading,roman,meaning,detail,extra};
add('machine','券売機','けんばいき','kenbaiki','Ticket vending machine.','券 = ticket, 売 = sell, 機 = machine. This machine sells meal tickets.','Korean 발권기 (發券機) is a related but different compound: a ticket-issuing machine.');
add('shoyu-shop','中華そば','ちゅうかそば','chūka soba','Another name for ramen.','Here it means the shop’s wheat-noodle ramen, not buckwheat soba.','中華 refers to Chinese-style food. A shop’s naming convention does not specify every ingredient.');
add('hakata-shop','博多とんこつ','はかた とんこつ','Hakata tonkotsu','Hakata-style pork-bone ramen.','博多 is Hakata, in Fukuoka. とんこつ is pork-bone broth. This shop uses thin noodles and sells refill tickets.');
add('recommended','おすすめ','おすすめ','osusume','Recommended.','The shop is drawing attention to this dish. It is not a separate size or topping.');
add('chicken-stock','鶏だし','とりだし','tori dashi','Chicken stock.','鶏 is chicken; だし is stock. This describes the base broth, while 醤油 and 塩 describe the seasoning.');
add('egg-included','味玉入り','あじたまいり','ajitama iri','Seasoned egg included.','入り means “containing” or “with.” This bowl already comes with an egg. An extra 味玉 ticket buys another one.');
add('topping','トッピング','トッピング','toppingu','Toppings / add-ons.','These tickets add something to a bowl. They do not buy another ramen.');
add('more-noodles','麺増量','めんぞうりょう','men zōryō','More noodles.','麺 means noodles; 増量 means an increased quantity. In this shop, 大盛 increases the initial serving.');
add('rice-heading','ごはん','ごはん','gohan','Rice.','This header groups the rice side dishes. ご飯 can also mean a meal in other contexts.');
add('yen','円','えん','en','Yen.','The number followed by 円 is the ticket price. 850円 means 850 yen.','¥ and 円 both indicate yen in these price labels.');
add('tax','価格はすべて税込です','かかくは すべて ぜいこみです','kakaku wa subete zeikomi desu','All prices include tax.','税込 means tax included. The price on the button is the amount deducted from your credit.');
add('change-empty','つり銭切れ','つりせんぎれ','tsurisen-gire','Out of change.','This is an unlit status indicator here. It does not say that your change is ready.','つり銭 is change money; 切れ means the supply has run out. Some machines restrict sales when they cannot make change.');
add('buy-first','先に食券をお買い求めください','さきに しょっけんを おかいもとめください','saki ni shokken o okaimotome kudasai','Please buy a meal ticket first.','先に means “beforehand” or “first.” お買い求めください is a polite shop instruction to purchase something.');
add('insert-instructions','お金を入れてから ご希望のボタンを押してください','おかねを いれてから ごきぼうの ボタンを おしてください','okane o irete kara gokibō no botan o oshite kudasai','Insert money, then press the button you want.','〜てから means “after doing.” The order is money first, menu button second.');
add('choose-button','ご希望のボタンを押してください','ごきぼうの ボタンを おしてください','gokibō no botan o oshite kudasai','Please press the button you want.','ご希望 means your preferred choice; 押す means to press. Pressing a lit menu button purchases its ticket.');
add('wait','しばらくお待ちください','しばらく おまちください','shibaraku omachi kudasai','Please wait a moment.','The machine is completing an operation. Do not repeatedly press the menu button.');
add('return-instructions','お買い求めの後は おつりボタンを押してください','おかいもとめの あとは おつりボタンを おしてください','okaimotome no ato wa otsuri botan o oshite kudasai','After purchasing, press the change button.','This shop’s machine keeps unused credit until you press おつり・返却.');
add('forget-warning','取り忘れにご注意ください','とりわすれに ごちゅういください','toriwasure ni gochūi kudasai','Please remember to collect your belongings.','Here it warns you not to leave tickets in the outlet. 取り忘れ is forgetting to take something.');
add('take','お取りください','おとりください','otori kudasai','Please take it / collect it.','This appears when tickets or change are ready in the outlet.');
add('sheet-counter','枚','まい','mai','Counter for flat objects.','1枚 means one ticket; 2枚 means two tickets. 枚 also counts sheets of paper and other flat objects.');
add('vender','TICKET VENDER','チケットベンダー','chiketto bendā','Ticket vending machine.','An English hardware label. “Vender” is a spelling found on real machine branding.');
add('standard','定番','ていばん','teiban','The standard / regular choice.','The shop’s usual basic ramen, as opposed to a special version or variation.');
add('more-pork','肉増し','にくまし','niku mashi','Extra meat.','肉 means meat; 増し means more. On this button the larger pork serving is included in the bowl price.');
add('more-negi','ねぎ増し','ねぎまし','negi mashi','Extra spring onion.','This bowl includes more spring onion. A separate ねぎ ticket would add another portion.');
add('mayu','黒マー油','くろマーゆ','kuro māyu','Black garlic oil.','A roasted-garlic oil used to add a dark color and toasted flavor to the broth. The black bowl uses the same pork-bone base.');
add('spicy','辛味','からみ','karami','Spiciness / spicy seasoning.','The red bowl adds spicy seasoning to the pork-bone broth. This is not a separate soup made only from chili.');
add('tonkotsu','豚骨ラーメン','とんこつ ラーメン','tonkotsu rāmen','Pork-bone ramen.','豚 means pig; 骨 means bone. This shop’s basic bowl has thin noodles, pork, spring onion and wood-ear mushrooms.');
add('chashu-bowl','チャーシュー麺','チャーシューめん','chāshū men','Ramen with extra chashu pork.','A complete bowl with extra sliced pork. The separate チャーシュー ticket is just the extra topping.');
add('hakata-egg','味玉豚骨','あじたま とんこつ','ajitama tonkotsu','Pork-bone ramen with a seasoned egg.','A complete bowl with an egg included.');
add('hakata-negi','ねぎ豚骨','ねぎ とんこつ','negi tonkotsu','Pork-bone ramen with extra spring onion.','A complete bowl. The additional spring onion is included in this price.');
add('black','黒ラーメン','くろ ラーメン','kuro rāmen','Black garlic-oil ramen.','This shop’s pork-bone ramen with 黒マー油, roasted-garlic oil. The name describes this shop’s version, not a universal recipe.');
add('red','赤ラーメン','あか ラーメン','aka rāmen','Spicy red ramen.','This shop adds spicy seasoning to its pork-bone broth. 赤 means red.');
add('noodle-refill','麺のおかわり','めんの おかわり','men no okawari','Another serving of noodles.','A refill contains noodles, not a fresh bowl of soup. Keep broth from your original bowl.');
add('kaedama','替玉','かえだま','kaedama','Noodle refill.','Buy the ticket now, keep it, then give it to the staff when you want more noodles. This shop does not take the refill ticket with the first bowl’s tickets.','替 means replace or change. Unlike 大盛, this is a separate serving added later to the broth you kept. Other shops may sell refills at the seat instead.');
add('half-kaedama','半替玉','はんかえだま','han-kaedama','Half a noodle refill.','A smaller serving of refill noodles. 半 means half. Keep this ticket until you request it.');
add('kikurage','きくらげ','きくらげ','kikurage','Wood-ear mushrooms.','An extra portion of the thin, dark mushrooms commonly served with Hakata-style ramen. Not seaweed.');
add('negi','ねぎ','ねぎ','negi','Spring onion.','An additional portion of chopped spring onion.');
add('chashu','チャーシュー','チャーシュー','chāshū','Chashu pork.','An extra portion of sliced prepared pork. This topping ticket does not include a bowl of ramen.');
add('mentai-rice','明太ごはん','めんたい ごはん','mentai gohan','Rice with seasoned pollock roe.','明太 is short for 明太子 (めんたいこ). This is a rice side dish.','Korean 명태 and Japanese 明太 share a word-history connection through the name for pollock; 明太子 refers to its roe.');
add('white-rice','白ごはん','しろごはん','shiro gohan','Plain white rice.','A side serving of rice, without the roe topping of 明太ごはん.');
add('gyoza','餃子','ぎょうざ','gyōza','Dumplings.','A side serving of pan-fried dumplings. Sold out in this practice shop.');
add('bite-gyoza','一口餃子','ひとくち ぎょうざ','hitokuchi gyōza','Bite-sized dumplings.','一口 means one mouthful. This describes small dumplings, not a single dumpling per ticket.');
add('beer','瓶ビール','びんビール','bin bīru','Bottled beer.','瓶 means bottle. This is a drink ticket, not part of the ramen price.');
add('drinks','お飲み物','おのみもの','onomimono','Drinks.','飲み物 is something to drink. The initial お makes the category label more polite.');
add('firmness-notice','麺のかたさは店員へ','めんの かたさは てんいんへ','men no katasa wa ten’in e','Tell the staff your noodle firmness preference.','This machine does not ask you to choose noodle firmness. The staff asks when you hand over the bowl tickets.');
add('refill-notice','替玉券はお手元に','かえだまけんは おてもとに','kaedama-ken wa otemoto ni','Keep your noodle-refill ticket with you.','Present it when you want the refill, not with the initial bowl ticket. This is the selected shop’s rule.');
add('firmness','麺のかたさは？','めんの かたさは','men no katasa wa?','How firm would you like your noodles?','The staff is asking about the noodles, not the strength of the soup. ふつう is a reasonable first choice.','やわめ = soft; ふつう = regular; かため = firm; バリカタ = extra firm. Available choices vary by shop.');

add('thanks','ありがとうございます。','ありがとうございます','arigatō gozaimasu','Thank you.','A polite thank-you you may hear from the staff after handing over your tickets.');
